/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/main-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Main Categories */
        get: operations["get_main_categories_main_categories_get"];
        put?: never;
        /** Create Main Category */
        post: operations["create_main_category_main_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sub-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sub Categories */
        get: operations["get_sub_categories_sub_categories_get"];
        put?: never;
        /** Create Sub Category */
        post: operations["create_sub_category_sub_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/main-categories/{main_category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Main Category
         * @description Delete an empty main category. One with sub-categories is refused.
         *
         *     Refused rather than cascaded: deleting "research literature" should not
         *     quietly take every document filed beneath it. Delete the sub-categories
         *     first -- each of those refiles its documents instead of destroying them.
         */
        delete: operations["delete_main_category_main_categories__main_category_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sub-categories/{sub_category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Sub Category
         * @description Delete a sub-category. Its documents are refiled, never destroyed.
         *
         *     200 with a count, not an empty 204: the documents move, and the caller
         *     should be told where. The move is done by a trigger in the database, so
         *     psql behaves the same way.
         */
        delete: operations["delete_sub_category_sub_categories__sub_category_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat */
        post: operations["post_chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Crops */
        get: operations["get_crops_crops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Items
         * @description Published documents; `status=all` adds drafts and needs an editor or admin token.
         *
         *     The default path ignores the token: the frontend sends one on every request, and a 401 on it
         *     would end the session.
         */
        get: operations["get_items_items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Item
         * @description Hard-delete a document and its chunks; 200 returns the deleted row, since there is no
         *     backup or audit record to recover it from.
         */
        delete: operations["delete_item_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invites */
        get: operations["list_invites_members_invites_get"];
        put?: never;
        /** Create Invite */
        post: operations["create_invite_members_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_members_invites__invite_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_members_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_members_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_members_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Member */
        delete: operations["delete_member_members__member_id__delete"];
        options?: never;
        head?: never;
        /** Update Member */
        patch: operations["update_member_members__member_id__patch"];
        trace?: never;
    };
    "/members/{member_id}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock Member */
        post: operations["unlock_member_members__member_id__unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieval/{crop_slug}/{topic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topic Set
         * @description The complete published document set for one crop and one topic.
         *
         *     No `limit`. Every published document sharing `topic` for this crop comes
         *     back, or the request is refused (413) naming the topic and its document
         *     count, per Rule 3's refusal step (see assemble_within_budget) -- never a
         *     silent slice.
         */
        get: operations["get_topic_set_retrieval__crop_slug___topic__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Abstention */
        Abstention: {
            /** Reason */
            reason: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["CitedDocument"][];
            /**
             * Topics Used
             * @default []
             */
            topics_used: string[];
            /**
             * Topics Used Crops
             * @default []
             */
            topics_used_crops: string[];
            /**
             * Dropped
             * @default []
             */
            dropped: components["schemas"]["DroppedChatTopic"][];
            abstained?: components["schemas"]["Abstention"] | null;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /**
         * CitedDocument
         * @description A RetrievedDocument plus the key the answer cites it by ("S1").
         */
        CitedDocument: {
            /** Id */
            id: number;
            /** Topic */
            topic?: string | null;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Source */
            source: string;
            /** Reference */
            reference: string;
            /** Url */
            url: string;
            /** Read Directly */
            read_directly: boolean;
            /** Via */
            via?: string | null;
            /** Condition */
            condition?: string | null;
            /** Licence Note */
            licence_note?: string | null;
            /** Key */
            key: string;
            /** Crop Slug */
            crop_slug?: string | null;
        };
        /**
         * CropResponse
         * @example {
         *       "common_name": "basil",
         *       "ecocrop_id": 1547,
         *       "id": 1,
         *       "scientific_name": "Ocimum basilicum",
         *       "slug": "basil"
         *     }
         */
        CropResponse: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Common Name */
            common_name: string;
            /** Scientific Name */
            scientific_name: string;
            /** Ecocrop Id */
            ecocrop_id?: number | null;
        };
        /** DroppedChatTopic */
        DroppedChatTopic: {
            /** Topic */
            topic: string;
            /** Score */
            score: number;
            /** Document Count */
            document_count: number;
            /** Context Chars */
            context_chars: number;
            /** Crop Slug */
            crop_slug?: string | null;
        };
        /**
         * DroppedTopic
         * @description A whole topic dropped to fit the budget -- named, never silently.
         */
        DroppedTopic: {
            /** Topic */
            topic: string;
            /** Score */
            score: number;
            /** Document Count */
            document_count: number;
            /** Context Chars */
            context_chars: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InviteAdminView
         * @description An open invite as an admin lists it. No code (it is shown once, at creation)
         *     and no code_hash: neither field exists here, so neither can leak.
         */
        InviteAdminView: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Email */
            email: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * InviteCreate
         * @description What an admin sends to create an invite. The role is limited to what
         *     INVITE_ROLES allows (never admin); the email, if given, binds the invite to
         *     that address (surrounding whitespace is allowed and stripped on save). The pattern
         *     also refuses NUL, which PostgreSQL rejects in text.
         */
        InviteCreate: {
            /**
             * Role
             * @default member
             * @enum {string}
             */
            role: "member" | "editor";
            /**
             * Expires In Days
             * @default 7
             */
            expires_in_days: number;
            /** Email */
            email?: string | null;
        };
        /**
         * InviteResponse
         * @description The only time the plaintext code is ever returned.
         */
        InviteResponse: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Role */
            role: string;
            /** Email */
            email: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * ItemCreate
         * @example {
         *       "body": "Reports a 29-35 °C optimum, conditioned on a stated daily light integral. Does not agree with the ECOCROP band; both are published and neither is ranked.",
         *       "condition": "DLI 19.5 mol·m⁻²·d⁻¹",
         *       "crop_id": 1,
         *       "published": false,
         *       "read_directly": false,
         *       "reference": "Walters & Currey (2019), HortScience 54(11):1915",
         *       "source": "Walters & Currey (2019)",
         *       "sub_category_id": 1,
         *       "title": "Walters & Currey on basil's optimal temperature",
         *       "topic": "optimal-temperature",
         *       "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10688745/",
         *       "via": "Walters, Tarr & Lopez (2023), PLoS One 18(11):e0294905"
         *     }
         */
        ItemCreate: {
            /** Sub Category Id */
            sub_category_id: number;
            /** Crop Id */
            crop_id: number;
            /** Topic */
            topic?: string | null;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Published
             * @default false
             */
            published: boolean;
            /** Source */
            source: string;
            /** Reference */
            reference: string;
            /** Url */
            url: string;
            /** Read Directly */
            read_directly: boolean;
            /** Via */
            via?: string | null;
            /** Condition */
            condition?: string | null;
            /** Licence Note */
            licence_note?: string | null;
        };
        /** ItemResponse */
        ItemResponse: {
            /** Sub Category Id */
            sub_category_id: number;
            /** Crop Id */
            crop_id: number;
            /** Topic */
            topic?: string | null;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Published
             * @default false
             */
            published: boolean;
            /** Source */
            source: string;
            /** Reference */
            reference: string;
            /** Url */
            url: string;
            /** Read Directly */
            read_directly: boolean;
            /** Via */
            via?: string | null;
            /** Condition */
            condition?: string | null;
            /** Licence Note */
            licence_note?: string | null;
            /** Id */
            id: number;
        };
        /**
         * MainCategoryCreate
         * @description Kind of knowledge: crop profile, research literature, cultivation
         *     practice, pests and disorders. A crop is not a category -- crops have
         *     their own table, so adding one does not require copying this tree (the seed
         *     still files each crop under its own main category).
         * @example {
         *       "name": "Research literature",
         *       "position": 1,
         *       "slug": "research-literature"
         *     }
         */
        MainCategoryCreate: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /**
         * MainCategoryResponse
         * @description `subcategories` must be loaded up front with selectinload() in crud.
         *
         *     Async SQLAlchemy cannot lazy-load a relationship on first access: it raises
         *     MissingGreenlet, which pydantic wraps in a ValidationError, so the request
         *     fails with a 500 (and `except MissingGreenlet` would not catch it).
         */
        MainCategoryResponse: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /**
             * Subcategories
             * @default []
             */
            subcategories: components["schemas"]["SubCategoryResponse"][];
        };
        /**
         * MemberAdminUpdate
         * @description What an admin may change on a member. extra="forbid": any other field
         *     (tokens_used_today, password_hash, ...) is a 422, not silently ignored. Only
         *     sent fields change; an explicit null is a 422 (the defaults are never validated).
         */
        MemberAdminUpdate: {
            /**
             * Role
             * @enum {string}
             */
            role?: "member" | "editor" | "admin";
            /** Tokens Budget Daily */
            tokens_budget_daily?: number;
            /** Is Active */
            is_active?: boolean;
        };
        /**
         * MemberAdminView
         * @description What an admin sees of a member: everything but the password hash.
         */
        MemberAdminView: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Tokens Used Today */
            tokens_used_today: number;
            /** Tokens Budget Daily */
            tokens_budget_daily: number;
            /**
             * Budget Window Start
             * Format: date
             */
            budget_window_start: string;
        };
        /** MemberCreate */
        MemberCreate: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
            /** Invite Code */
            invite_code: string;
        };
        /** MemberLogin */
        MemberLogin: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MemberResponse */
        MemberResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Tokens Used Today */
            tokens_used_today: number;
            /** Tokens Budget Daily */
            tokens_budget_daily: number;
            /**
             * Budget Window Start
             * Format: date
             */
            budget_window_start: string;
            /** Role */
            role: string;
        };
        /**
         * RetrievedDocument
         * @description One document as retrieval hands it on: prose plus its provenance.
         *
         *     Every provenance field of `Item` is here, none is optional-by-omission.
         *     A retrieved document that arrived without its source would be exactly the
         *     silent-winner problem in another costume -- the reader could not tell which
         *     of three disagreeing claims they were looking at.
         */
        RetrievedDocument: {
            /** Id */
            id: number;
            /** Topic */
            topic?: string | null;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Source */
            source: string;
            /** Reference */
            reference: string;
            /** Url */
            url: string;
            /** Read Directly */
            read_directly: boolean;
            /** Via */
            via?: string | null;
            /** Condition */
            condition?: string | null;
            /** Licence Note */
            licence_note?: string | null;
        };
        /**
         * SubCategoryCreate
         * @example {
         *       "main_category_id": 1,
         *       "name": "Temperature response",
         *       "position": 1,
         *       "slug": "temperature-response"
         *     }
         */
        SubCategoryCreate: {
            /** Main Category Id */
            main_category_id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /**
         * SubCategoryDeleteResponse
         * @description What the delete did: its documents were moved, not destroyed.
         *
         *     A trigger refiles them to "Uncategorised", so the endpoint answers 200 with
         *     the count instead of an empty 204 that would hide the move.
         */
        SubCategoryDeleteResponse: {
            /** Documents Refiled */
            documents_refiled: number;
            /** Refiled To */
            refiled_to: number;
        };
        /** SubCategoryResponse */
        SubCategoryResponse: {
            /** Id */
            id: number;
            /** Main Category Id */
            main_category_id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TopicSetResponse
         * @description The complete published document set for one crop and one topic.
         *
         *     `document_count` is not redundant beside `len(documents)`: it is the
         *     assertion this endpoint exists to make. A client reading only the count
         *     still sees a truncation, because a truncated list would have to disagree
         *     with it -- and nothing in this codebase writes the count from anything but
         *     the list it ships with.
         *
         *     The budget figures are reported on every successful response, not only on
         *     a refusal, so the margin is observable *before* a topic grows past it.
         */
        TopicSetResponse: {
            /** Crop Slug */
            crop_slug: string;
            /** Topic */
            topic: string;
            /** Document Count */
            document_count: number;
            /** Documents */
            documents: components["schemas"]["RetrievedDocument"][];
            /** Context Chars */
            context_chars: number;
            /** Context Char Budget */
            context_char_budget: number;
            /** Chars Per Token */
            chars_per_token: number;
            /**
             * Dropped
             * @default []
             */
            dropped: components["schemas"]["DroppedTopic"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_main_categories_main_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MainCategoryResponse"][];
                };
            };
        };
    };
    create_main_category_main_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MainCategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MainCategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sub_categories_sub_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubCategoryResponse"][];
                };
            };
        };
    };
    create_sub_category_sub_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubCategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubCategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_main_category_main_categories__main_category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                main_category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_sub_category_sub_categories__sub_category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sub_category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubCategoryDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crops_crops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropResponse"][];
                };
            };
        };
    };
    get_items_items_get: {
        parameters: {
            query?: {
                status?: "published" | "all";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_members_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                role?: ("member" | "editor" | "admin") | null;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberAdminView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_members_invites_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteAdminView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_members_invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_members_invites__invite_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_members_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_members_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_members_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    delete_member_members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberAdminView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_member_members__member_id__unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_set_retrieval__crop_slug___topic__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crop_slug: string;
                topic: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicSetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
